spring.application.name=course-management

# Cấu hình kết nối y như ảnh của bạn (chỉ đổi tên database ở cuối)
spring.datasource.url=jdbc:mysql://localhost:3306/quanlykhoahoc
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Bắt buộc phải có 2 dòng này để Spring Boot tự động tạo 7 bảng từ file Entity nhé:
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Cho phép dung lượng 1 file tối đa là 500MB
spring.servlet.multipart.max-file-size=1000MB

# Cho phép tổng dung lượng 1 lần request tối đa là 500MB
spring.servlet.multipart.max-request-size=1000MB